import json
import os
import re
import statistics

from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def get_llm_signal(text: str) -> dict:
    """Signal 1: ask an LLM to judge AI-likelihood. Returns {'ai_probability': float, 'reasoning': str}."""
    prompt = (
        "You are an expert at detecting AI-generated text. Analyze the following piece of writing "
        "and judge the probability that it was generated by an AI language model rather than written "
        "by a human. Consider tone consistency, generic phrasing, hedging language, and structural "
        "patterns common in LLM output.\n\n"
        "Respond ONLY with a JSON object of the form "
        '{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}.\n\n'
        f"TEXT:\n{text}"
    )
    try:
        resp = _get_client().chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=200,
        )
        content = resp.choices[0].message.content.strip()
        match = re.search(r"\{.*\}", content, re.DOTALL)
        data = json.loads(match.group(0) if match else content)
        prob = float(data.get("ai_probability", 0.5))
        prob = max(0.0, min(1.0, prob))
        return {"ai_probability": prob, "reasoning": data.get("reasoning", "")}
    except Exception as e:
        return {"ai_probability": 0.5, "reasoning": f"llm_signal_error: {e}"}


def get_stylometric_signal(text: str) -> dict:
    """Signal 2: structural heuristics. Returns {'ai_probability': float, 'metrics': {...}}."""
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"\b\w+\b", text.lower())

    if len(sentences) < 3 or len(words) < 20:
        return {
            "ai_probability": 0.5,
            "metrics": {"note": "text too short for reliable stylometric analysis"},
        }

    sentence_lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    length_variance = statistics.pvariance(sentence_lengths)

    type_token_ratio = len(set(words)) / len(words)

    punct_count = len(re.findall(r"[,;:\-—()\"']", text))
    punct_density = punct_count / max(len(text), 1)

    # Normalize each metric to [0,1] "AI-likelihood" contribution.
    # Low variance, low lexical diversity, low punctuation variety => more AI-like.
    variance_score = max(0.0, 1.0 - min(length_variance / 40.0, 1.0))
    diversity_score = max(0.0, 1.0 - min(type_token_ratio / 0.6, 1.0))
    punct_score = max(0.0, 1.0 - min(punct_density / 0.08, 1.0))

    ai_probability = (variance_score + diversity_score + punct_score) / 3.0

    return {
        "ai_probability": round(ai_probability, 4),
        "metrics": {
            "sentence_length_variance": round(length_variance, 2),
            "type_token_ratio": round(type_token_ratio, 4),
            "punctuation_density": round(punct_density, 4),
        },
    }
